### ISSUE TITLE
опечатка в коде

### ISSUE THREAD

**Issue by Deymaz** [matry-ny/09_10_samples#1]
`$migrations = array_filter(scandir($migrationsDir), function ($item) use ($executedMigrations) {
    return !in_array($item, array_merge(['.', '..'], $executedMigrations));
});
if (empty($migration)) {
    die("Database is up to date\r\n");
}`

if (empty($migration)) заменить на $migrations

**Comment by matry-ny** [comment]
Refactored to OOP style. Fixed in process.
